### ISSUE TITLE
IDA 6.6 NameError: name 'action_handler_t' is not defined

### ISSUE THREAD

**Issue by ret5et** [carlosgprado/JARVIS#1]
I don't know why but ...

```
JARVIS launcher initialized
name 'action_handler_t' is not defined
Traceback (most recent call last):
  File "C:\Program Files\IDA 6.6\python\idaapi.py", line 601, in IDAPython_ExecScript
    execfile(script, g)
  File "C:/Program Files/IDA 6.6/plugins/jarvis/jarvis.py", line 30, in <module>
    from jarvis.core.helpers.UI import install_ui_hooks
  File "C:/Program Files/IDA 6.6/plugins/jarvis\jarvis\core\helpers\UI.py", line 16, in <module>
    class InitBBHandler(action_handler_t):
NameError: name 'action_handler_t' is not defined
```

**Comment by carlosgprado** [comment]
JARVIS uses some new GUI features of IDA, which were introduced on version 6.7 (see http://www.hexblog.com/?p=886). At the moment, there are no plans of making it backwards compatible with versions of IDA prior to 6.7
