### ISSUE TITLE
Add exception catching to CustomWidget

### ISSUE THREAD

**Issue by carlosgprado** [carlosgprado/JARVIS#2]
Traceback (most recent call last):
  File "C:/Program Files (x86)/IDA 6.8/plugins/jarvis\jarvis\widgets\CustomWidget.py", line 248, in **lt**
    return float(self.text()) < float(x.text())
ValueError: could not convert string to float: cmp     r10d, 1

**Comment by carlosgprado** [comment]
Traceback (most recent call last):
  File "C:/Program Files (x86)/IDA 6.8/plugins/jarvis\jarvis\widgets\CustomWidget.py", line 248, in __lt__
    return float(self.text()) < float(x.text())
ValueError: could not convert string to float: cmp     r10d, 1
